### ISSUE TITLE
node-pre-gyp dependency not found in PATH by install script

### ISSUE THREAD

**Issue by sarneaud** [cloudfoundry/yarn-cnb#3]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

pack v0.2.1

What version of the buildpack you are using?

0.0.6 (from cloudfoundry/cnd:0.0.2-cflinuxfs3 builder image)

If you were attempting to accomplish a task, what was it you were attempting to do?

Build an image from an existing Yarn-based app using the bcrypt npm module.

What did you expect to happen?

A image to be built and to show in `docker images`.

What was the actual behavior?

```
[builder] [4/4] Building fresh packages...
[builder] error /layers/org.cloudfoundry.yarn/node_modules/node_modules/bcrypt: Command failed.
[builder] Exit code: 127
[builder] Command: node-pre-gyp install --fallback-to-build
[builder] Arguments:
[builder] Directory: /layers/org.cloudfoundry.yarn/node_modules/node_modules/bcrypt
[builder] Output:
[builder] /bin/sh: 1: node-pre-gyp: not found
[builder] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[builder] unable to install node_modules: exit status 127
[builder] Error: failed to build: exit status 105

ERROR: failed with status code: 7
```
`node-pre-gyp` is in the bcrypt module's dependency list.

Can you provide a sample app?

A minimal app with `npm init` and `yarn add bcrypt` is enough to reproduce for me.  (A minimal app with `npm install --save bcrypt` builds okay with the nodejs buildpack.)

Building with
`pack build --builder cloudfoundry/cnb:cflinuxfs3 appname`

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by kardolus** [comment]
@sarneaud thanks for bringing this to our attention.

I created a simple yarn app here that can be used to reproduce this issue: https://github.com/kardolus/yarn_bcrypt

We will prioritize this early next week in our IPM meeting.

**Comment by shanks3012** [comment]
The fix has been made and is currently on master. It will be included in the next release as well. Please reopen if you have further issues! Thanks.
